### ISSUE TITLE
Build Error -  cannot find symbol DartUiIsolatePlugin

### ISSUE THREAD

**Issue by rlueders** [chipweinberger/dart_ui_isolate#1]
I tried switching from Flutter Isolate to this new package, but get the following error when building the project. 

error: cannot find symbol
      flutterEngine.getPlugins().add(new com.lib.dart_ui_isolate.dart_ui_isolate.DartUiIsolatePlugin());
                                                                                ^
  symbol:   class DartUiIsolatePlugin
  location: package com.lib.dart_ui_isolate.dart_ui_isolate

**Comment by chipweinberger** [comment]
ya i didn't test android yet. 

wanna help? open a pr?

**Comment by rlueders** [comment]
I'm seeing build errors on IOS as well.   I will stick with the Flutter Isolate plugin for now.

ARC Semantic Issue (Xcode): No known class method for selector 'lookupGeneratedPluginRegistrant'
/.pub-cache/hosted/pub.dev/dart_ui_isolate-1.0.0/ios/Classes/DartUiIsolatePlugin.m:69:26

ARC Semantic Issue (Xcode): No known instance method for selector 'registerWithRegistry:'
/.pub-cache/hosted/pub.dev/dart_ui_isolate-1.0.0/ios/Classes/DartUiIsolatePlugin.m:69:59

**Comment by chipweinberger** [comment]
ok i'll fix it.

you can copy any missing code from flutter_isolate 

The main reason for this package is that it supports FlutterEngineGroup which saves 100s of megabytes of memory.

So this package will be better than flutter_isolate.

The isolates also spawn *much* faster.

**Comment by chipweinberger** [comment]
Ive fixed the build errors in 1.1.0. 

I have not tested it yet though on iOS and Android. I've only tested macOS so far, which works.
