### ISSUE TITLE
What's the current state of ui isolates?

### ISSUE THREAD

**Issue by ignatz** [chipweinberger/dart_ui_isolate#3]
I remember trying this package in the past and I remember it working. I was just trying it again and am always getting

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method spawn_isolate on channel com.lib.dart_ui_isolate/control)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
```

Given the in-flux state of this feature in the engine, I thought the method channel API might have changed. I tried various flutter versions from latest head to 3.19.2 and several random points in between but I couldn't get it to work. Arguably it's also late, so am I just holding it wrong?

**Comment by chipweinberger** [comment]
You should say what platform you are on. You should always give this info when filing issues.

Current State:
1. iOS & Mac are tested and working, last I checked
2. I have not tested android yet. Feel free to open a PR if you can fix it. Look at `flutter_isolate` for inspiration.

Basically, I'm just taking the code from `flutter_isolate` and removing the code related to plugins.


You should be using the example app when testing, and you should fully quit and relaunch your app.

**Comment by ignatz** [comment]
Linux. Which version of flutter did you validate? That was sort of the entire question. I did use the stock example and tried various flutter versions, which does require app restarts

**Comment by chipweinberger** [comment]
linux is not supported. thats why you are geting this error. only ios, android, macos.

**Comment by ignatz** [comment]
I guess I must have run the android emulator before 🤷‍♀️. Thanks, much appreciated
